config/routes.rb
Rails.application.routes.draw do
  # resources :identification_types
  resources :academic_programs
  resources :academic_departaments
  resources :faculties
  resources :users, param: :uuid
  devise_for :users, :skip => [:registrations],
    path: '',
    path_names: {
      sign_in: 'signin',
      sign_out: 'signout',
      sign_up: 'get-started',
      password: 'password'
    },
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
      confirmations: "users/confirmations"
    }

  devise_scope :user do
    authenticated :user do
      root 'users/profile#show', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :users, path: "/u" do
    get 'profile', to: 'profile#show'
    get 'new-user', to: 'registrations#new'
  end

  namespace :self_evaluations, path: "/acreditacion" do
    get 'muestreos', to: 'sampling_instruments#index', as: "sampling_instruments"
    namespace :sampling_instruments, path: "/muestreos" do
      resources :students, path: 'estudiantes', param: :code, only: [:index] do
        collection { post :import }
        collection { get '/:semesters', to: 'students#index_semester', as: "index_semester_other"}
        collection { post :index_semester_post }
      end
      resources :teachers, path: 'profesores', param: :code, only: [:index] do
        collection { post :import }
      end
      get 'formula', to: 'sampling_formula#index', as: "sampling_formula"
    end
  end
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :academic_programs, dependent: :destroy
  has_many :academic_departaments, dependent: :destroy
  validates :name, :code, presence: true
  validates :code, uniqueness: true
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
    authorize @faculties
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
    authorize @faculty
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
    authorize @faculty
  end

  # GET /faculties/1/edit
  def edit
    authorize @faculty
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)
    authorize @faculty

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'La facultad ha sido creada correctamente.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      authorize @faculty
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Se ha actualizado la facultad correctamente.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    authorize @faculty
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Se ha eliminado la facultad correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def faculty_params
      params.require(:faculty).permit(:name, :code)
    end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_form.html.erb
<div class="card-text">
  <%= form_with(model: faculty, local: true) do |form| %>
    <% if faculty.errors.any? %>
      <%= render 'shared/error_messages', resource: faculty%>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :code %>
      <%= form.text_field :code, class: "form-control" %>
    </div>

    <div class="actions">
      <%= link_to(request.referrer, class: "btn btn-custom-2 float-right") do %>
        Volver atras
      <% end %>
      <%= form.submit "Enviar formulario", class: "btn btn-success btn-index-create float-right mr-2" %>
    </div>
  <% end %>
</div>

app/views/faculties/edit.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Editar facultad</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Facultad</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= render 'form', faculty: @faculty %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/faculties/index.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Facultades</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Listado de las facultades en la UFPS</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <% if !@faculties.count.zero? %>
                  <div class="table-responsive">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th>Nombre</th>
                          <th>Codigo</th>
                          <th colspan="3">Opciones</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @faculties.each do |faculty| %>
                          <tr>
                            <td><%= faculty.name %></td>
                            <td><%= faculty.code %></td>
                            <td>
                              <%= link_to(faculty_path(faculty.id), class: "") do %>
                              <i class="fas fa-eye"></i>
                              <% end %>
                            </td>
                            <td>
                              <%= link_to(edit_faculty_path(faculty), class: "") do %>
                              <i class="fas fa-edit"></i>
                              <% end %>
                            </td>
                            <td>
                              <%= link_to(faculty_path(faculty.id), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "") do %>
                                <i class="fas fa-trash-alt"></i>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                    <%= link_to 'Crear nueva facultad', new_faculty_path, class: "btn btn-success btn-index-create float-right", role: "button" %>
                  </div>
                  <% else %>
                  <h2>No existen facultades en estos momentos, por favor, introduce los datos de la facultad y añadela</h2>
                  <%= link_to 'Crear nueva facultad', new_faculty_path, class: "btn btn-success btn-index-create float-right", role: "button" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/faculties/new.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Registrar una nueva facultad</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">

          <!-- /.card-header -->
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= render 'form', faculty: @faculty %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/faculties/show.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Datos de la facultad</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <tbody>
                      <tr role="row" class="odd">
                        <td class="sorting_1">Codigo</td>
                        <td><%= @faculty.code %></td>
                      </tr>
                      <tr role="row" class="even">
                        <td class="sorting_1">Nombre</td>
                        <td><%= @faculty.name %></td>
                      </tr>
                    </tbody>
                  </table>
                  <%= link_to(faculties_path, class: "btn btn-custom-2 float-right ") do %>
                    Volver atras
                  <% end %>

                  <%= link_to(edit_faculty_path(@faculty), class: "btn btn-success float-right mr-2") do %>
                    Editar facultad
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>