config/routes.rb
Rails.application.routes.draw do
  # resources :identification_types
  resources :academic_programs
  resources :academic_departaments
  resources :faculties
  resources :users, param: :uuid
  devise_for :users, :skip => [:registrations],
    path: '',
    path_names: {
      sign_in: 'signin',
      sign_out: 'signout',
      sign_up: 'get-started',
      password: 'password'
    },
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
      confirmations: "users/confirmations"
    }

  devise_scope :user do
    authenticated :user do
      root 'users/profile#show', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :users, path: "/u" do
    get 'profile', to: 'profile#show'
    get 'new-user', to: 'registrations#new'
  end

  namespace :self_evaluations, path: "/acreditacion" do
    get 'muestreos', to: 'sampling_instruments#index', as: "sampling_instruments"
    namespace :sampling_instruments, path: "/muestreos" do
      resources :students, path: 'estudiantes', param: :code, only: [:index] do
        collection { post :import }
        collection { get '/:semesters', to: 'students#index_semester', as: "index_semester_other"}
        collection { post :index_semester_post }
      end
      resources :teachers, path: 'profesores', param: :code, only: [:index] do
        collection { post :import }
      end
      get 'formula', to: 'sampling_formula#index', as: "sampling_formula"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include UniversalIdentifiable
  belongs_to :academic_program, optional: true
  belongs_to :academic_departament, optional: true
  belongs_to :identification_type

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:code, :document_number]

  validates :email, :name, :lastname, :code, :document_number, :contact_number, presence: true
  validates :code, :document_number, :email, :contact_number, uniqueness: true
  validates_uniqueness_of :academic_program_id, allow_blank: true

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout "public"
  protected

  def after_resetting_password_path_for(_resource)
    unauthenticated_root_path
  end
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < ApplicationController
  before_action :authenticate_user!
  before_action :load_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def load_user
    @user = User.find_by(uuid: params[:uuid])
  end

  def user_params
    params.require(:user).permit(:name, :lastname, :email, :document_number, :contact_number,
      :identification_type_id, :password, :password_confirmation)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :authenticate_user!
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:code, :name, :lastname, :document_number,
       :email, :contact_number, :identification_type_id, :academic_departament_id, :academic_program_id,
       :password])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:code, :name, :lastname, :document_number,
       :email, :contact_number, :identification_type_id, :academic_departament_id, :academic_program_id,
       :password])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout "public", only: [:new]
  before_action :configure_sign_in_params, only: [:create]


  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:code, :document_number])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.with_role :director_de_programa
    authorize @users
  end

  def show
    authorize @user
  end

  def new
    @user = User.new
    academics_programs_ocuped = []
    User.joins(:academic_program).each do |user|
      academics_programs_ocuped.push(user.academic_program.id)
    end
    @academic_programs = AcademicProgram.where.not(id: academics_programs_ocuped)
    authorize @user
  end

  def edit
    academics_programs_ocuped = []
    User.joins(:academic_program).each do |user|
      academics_programs_ocuped.push(user.academic_program.id)
    end
    @academic_programs = AcademicProgram.where.not(id: academics_programs_ocuped)
    authorize @user
  end

  def create
    @user = User.new(user_params)
    user_modify
    authorize @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Se ha actualizado el usuario correctamente.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      authorize @user
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Se ha actualizado el usuario correctamente.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Se ha eliminado el usuario correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find_by(uuid: params[:uuid])
    end

    def user_params
      params.require(:user).permit(:name, :lastname, :code, :email, :document_number, :contact_number,
        :identification_type_id, :academic_departament_id, :academic_program_id, :password, :password_confirmation)
    end

    def user_modify
      @user.update(password: "#{@user.document_number}"+"UFPS"+"#{@user.code}",
        password_confirmation: "#{@user.document_number}"+"UFPS"+"#{@user.code}")
      @user.add_role :director_de_programa
    end
end

app/views/users/_form.html.erb
<div class="card-text">
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <%= render 'shared/error_messages', resource: user%>
    <% end %>

    <% if current_user.has_role? :director_de_comite %>
    <div class="form-group">
      <%= form.label :code, "Codigo" %>
      <%= form.text_field :code, class: "form-control" %>
    </div>
    <% end %>
    <div class="form-group">
      <%= form.label :email, "Correo electronico" %>
      <%= form.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :name, "Nombre(s)" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :lastname, "Apellido(s)" %>
      <%= form.text_field :lastname, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :identification_type_id, "Tipo de identificacion" %>
      <%= form.select(:identification_type_id, IdentificationType.all.collect { |i| [i.description, i.id ] }, {}, { id: "user_identification_type_id", class: "form-control" }) %>
    </div>

    <div class="form-group">
      <%= form.label :document_number, "Numero de documento" %>
      <%= form.text_field :document_number, class: "form-control", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :contact_number, "Numero de contacto" %>
      <%= form.text_field :contact_number, class: "form-control" %>
    </div>

    <% if (current_user.has_role? :director_de_comite) && (user.uuid? ? (user.has_role? :director_de_programa) : true)%>
    <div class="form-group">
      <%= form.label :academic_program_id, "Programa academico" %>
      <%= form.select(:academic_program_id, academic_programs.collect { |a| [a.name, a.id ] }, {}, { id: "user_academic_program_id", class: "form-control" }) %>
    </div>
    <% end %>

    <div class="actions">
      <% if current_user.has_role? :director_de_comite %>
        <%= link_to(request.referrer, class: "btn btn-custom-2 float-right") do %>
          Volver atras
        <% end %>
      <% else %>
        <%= link_to(users_profile_path, class: "btn btn-custom-2 float-right") do %>
          Volver al perfil
        <% end %>
      <% end %>
      <%= form.submit "Enviar formulario", class: "btn btn-success btn-index-create float-right mr-2" %>
    </div>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Editar datos personales</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Datos personales</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= render 'form', user: @user, academic_programs: @academic_programs %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Directores de programa</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Listado de los directores de programa</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <% if !@users.count.zero? %>
                  <div class="table-responsive">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th>Codigo</th>
                          <th>Nombre(s)</th>
                          <th>Apellido(s)</th>
                          <th>Tipo de documento</th>
                          <th>Numero de documento</th>
                          <th>Correo electronico</th>
                          <th>Programa academico</th>
                          <th colspan="3">Opciones</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @users.each do |user| %>
                          <tr>
                            <td><%= user.code %></td>
                            <td><%= user.name %></td>
                            <td><%= user.lastname %></td>
                            <td><%= user.identification_type.summary_description %></td>
                            <td><%= user.document_number %></td>
                            <td><%= user.email %></td>
                            <td><%= user.academic_program.name %></td>

                            <td>
                              <%= link_to(user_path(user.uuid), class: "") do %>
                              <i class="fas fa-eye"></i>
                              <% end %>
                            </td>
                            <td>
                              <%= link_to(edit_user_path(user), class: "") do %>
                              <i class="fas fa-edit"></i>
                              <% end %>
                            </td>
                            <td>
                              <%= link_to(user_path(user.uuid), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "") do %>
                                <i class="fas fa-trash-alt"></i>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                    <%= link_to 'Crear nuevo director de programa', new_user_path, class: "btn btn-success btn-index-create float-right", role: "button" %>
                  </div>
                  <% else %>
                  <h3>No existen directores de programa en estos momentos, por favor, introduce los datos del director de programa y registralo</h3>
                  <%= link_to 'Crear nuevo director de programa', new_user_path, class: "btn btn-success btn-index-create float-right", role: "button" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Registra un nuevo director de programa</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">

          <!-- /.card-header -->
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= render 'form', user: @user, academic_programs: @academic_programs %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Ver datos personales</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Verificacion de datos</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <tbody>
                      <tr role="row" class="odd">
                        <td class="sorting_1">Codigo</td>
                        <td><%= @user.code %></td>
                      </tr>
                      <tr role="row" class="even">
                        <td class="sorting_1">Tipo documento</td>
                        <td><%= @user.identification_type.summary_description %></td>
                      </tr>
                      <tr role="row" class="odd">
                        <td class="sorting_1">Documento</td>
                        <td><%= @user.document_number %></td>
                      </tr>
                      <tr role="row" class="even">
                        <td class="sorting_1">Nombre(s)</td>
                        <td><%= @user.name %></td>
                      </tr>
                      <tr role="row" class="odd">
                        <td class="sorting_1">Apellido(s)</td>
                        <td><%= @user.lastname %></td>
                      </tr>

                      <tr role="row" class="even">
                        <td class="sorting_1">Telefono</td>
                        <td><%= @user.contact_number %></td>
                      </tr>

                      <% if @user.academic_program != nil %>
                      <tr role="row" class="odd">
                        <td class="sorting_1">Programa academico</td>
                        <td><%= @user.academic_program.name %></td>
                      </tr>

                      <tr role="row" class="even">
                        <td class="sorting_1">Facultad</td>
                        <td><%= @user.academic_program.faculty.name %></td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <% if current_user.has_role? :director_de_comite%>
                    <%= link_to(users_path, class: "btn btn-custom-2 float-right ") do %>
                      Volver atras
                    <% end %>
                  <% else %>
                    <%= link_to(authenticated_root_path, class: "btn btn-custom-2 float-right ") do %>
                      Volver al perfil
                    <% end %>
                  <% end %>

                  <%= link_to(edit_user_path(@user), class: "btn btn-success float-right mr-2") do %>
                    Editar usuario
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>