config/routes.rb
Rails.application.routes.draw do
  # resources :identification_types
  resources :academic_programs
  resources :academic_departaments
  resources :faculties
  resources :users, param: :uuid
  devise_for :users, :skip => [:registrations],
    path: '',
    path_names: {
      sign_in: 'signin',
      sign_out: 'signout',
      sign_up: 'get-started',
      password: 'password'
    },
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
      confirmations: "users/confirmations"
    }

  devise_scope :user do
    authenticated :user do
      root 'users/profile#show', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :users, path: "/u" do
    get 'profile', to: 'profile#show'
    get 'new-user', to: 'registrations#new'
  end

  namespace :self_evaluations, path: "/acreditacion" do
    get 'muestreos', to: 'sampling_instruments#index', as: "sampling_instruments"
    namespace :sampling_instruments, path: "/muestreos" do
      resources :students, path: 'estudiantes', param: :code, only: [:index] do
        collection { post :import }
        collection { get '/:semesters', to: 'students#index_semester', as: "index_semester_other"}
        collection { post :index_semester_post }
      end
      resources :teachers, path: 'profesores', param: :code, only: [:index] do
        collection { post :import }
      end
      get 'formula', to: 'sampling_formula#index', as: "sampling_formula"
    end
  end
end

app/views/shared/_alert.html.erb
<% if flash.present? %>
  <div class="container mx-auto z-40">
    <% flash.each do |msg_type, msg| %>
      <% if msg.is_a?(String) %>
        <%= flash_alert(msg_type, msg) %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-warning alert-dismissible text-justify" role="alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
    <i class="fa fa-exclamation-triangle"></i>
    Ha(n) ocurrido <%= pluralize(resource.errors.count, "error") %>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <strong>Copyright © 2020 Camilo Obando.</strong>
  All rights reserved.
</footer>

app/views/shared/_header.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom nav-bar-custom">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#">
        <i class="fas fa-bars text-white-nav"></i >
      </a>
    </li>

  </ul>
  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <span class="nav-link" data-toggle="dropdown" href="#">
        <i class="fas fa-user-tie text-white-nav"></i>
        <span class="float-right text-sm text-white-nav"><%= current_user.name %></span>
      </span>
    </li>

    <li class="nav-item">
      <%= link_to(destroy_user_session_path, method: :delete, class: "nav-link") do %>
        <i class="fas fa-sign-out-alt text-white-nav"></i>
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->

  <%= link_to(authenticated_root_path, class: "brand-link") do %>
  <span class="brand-text font-weight-light">AutoevaSoft</span>
  <% end %>
  <!-- Sidebar -->
  <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 652px;">
    <div class="sidebar" style="min-height: 652px; overflow: hidden; width: auto; height: 652px;">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="http://placehold.it/160x160" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <%= link_to(current_user.name, users_profile_path, class: "d-block")%>
        </div>
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item has-treeview <%=active_section([users_profile_path, edit_user_path(current_user)])%>">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-user-friends"></i>
              <p>
                Informacion personal
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item <%=active_path(users_profile_path)%>">
                <%= link_to(users_profile_path, class: "nav-link") do %>
                <i class="far fa-circle nav-icon"></i>
                <p>Datos personales</p>
                <% end %>
              </li>
              <li class="nav-item <%=active_path(edit_user_path(current_user)) %>">
                <%= link_to(edit_user_path(current_user), class: "nav-link") do %>
                <i class="far fa-circle nav-icon"></i>
                <p>Editar datos personales</p>
                <% end %>
              </li>
            </ul>
          </li>
          <% if current_user.has_role? :director_de_comite%>
          <li class="nav-item has-treeview <%=active_section([faculties_path, academic_programs_path, academic_departaments_path])%>">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-building"></i>
              <p>
                Infraestructura fisica
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item <%=active_path(faculties_path) %>">
                <%= link_to(faculties_path, class: "nav-link") do %>
                <i class="far fa-circle nav-icon"></i>
                <p>Facultades</p>
                <% end %>
              </li>
              <li class="nav-item <%=active_path(academic_programs_path) %>">
                <%= link_to(academic_programs_path, class: "nav-link") do %>
                <i class="far fa-circle nav-icon"></i>
                <p>Programas academicos</p>
                <% end %>
              </li>
              <li class="nav-item <%=active_path(academic_departaments_path) %>">
                <%= link_to(academic_departaments_path, class: "nav-link") do %>
                <i class="far fa-circle nav-icon"></i>
                <p>Departamentos</p>
                <% end %>
              </li>
            </ul>
          </li>

          <li class="nav-item has-treeview <%=active_section([users_path])%>">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-people-carry"></i>
              <p>
                Recurso humano
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item <%=active_path(users_path) %>">
                <%= link_to(users_path, class: "nav-link") do %>
                <i class="far fa-circle nav-icon"></i>
                <p>Directores de programa</p>
                <% end %>
              </li>
            </ul>
          </li>
          <% end %>

          <li class="nav-item has-treeview <%=active_section([self_evaluations_sampling_instruments_path, import_self_evaluations_sampling_instruments_students_path,
        index_semester_post_self_evaluations_sampling_instruments_students_path,
        self_evaluations_sampling_instruments_students_path])%>">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chart-line"></i>
              <p>
                Autoevaluacion
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <% if current_user.has_role? :director_de_comite%>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Encuestas</p>
                </a>
              </li>
              <% end %>
              <% if current_user.has_role? :director_de_programa%>
              <li class="nav-item <%=active_path(self_evaluations_sampling_instruments_path) %>">
                <%= link_to(self_evaluations_sampling_instruments_path, class: "nav-link") do %>
                <i class="far fa-circle nav-icon"></i>
                <p>Muestreo de instrumentos</p>
                <% end %>
              </li>
              <% end %>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>