config/routes.rb
Rails.application.routes.draw do
  # resources :identification_types
  resources :academic_programs
  resources :academic_departaments
  resources :faculties
  resources :users, param: :uuid
  devise_for :users, :skip => [:registrations],
    path: '',
    path_names: {
      sign_in: 'signin',
      sign_out: 'signout',
      sign_up: 'get-started',
      password: 'password'
    },
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
      confirmations: "users/confirmations"
    }

  devise_scope :user do
    authenticated :user do
      root 'users/profile#show', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :users, path: "/u" do
    get 'profile', to: 'profile#show'
    get 'new-user', to: 'registrations#new'
  end

  namespace :self_evaluations, path: "/acreditacion" do
    get 'muestreos', to: 'sampling_instruments#index', as: "sampling_instruments"
    namespace :sampling_instruments, path: "/muestreos" do
      resources :students, path: 'estudiantes', param: :code, only: [:index] do
        collection { post :import }
        collection { get '/:semesters', to: 'students#index_semester', as: "index_semester_other"}
        collection { post :index_semester_post }
      end
      resources :teachers, path: 'profesores', param: :code, only: [:index] do
        collection { post :import }
      end
      get 'formula', to: 'sampling_formula#index', as: "sampling_formula"
    end
  end
end

app/models/academic_departament.rb
class AcademicDepartament < ApplicationRecord
  has_many :users
  has_many :teachers
  belongs_to :faculty
  validates :name, :code, presence: true
  validates :code, uniqueness: true
end

app/controllers/academic_departaments_controller.rb
class AcademicDepartamentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_academic_departament, only: [:show, :edit, :update, :destroy]

  # GET /academic_departaments
  # GET /academic_departaments.json
  def index
    @academic_departaments = AcademicDepartament.all
    authorize @academic_departaments
  end

  # GET /academic_departaments/1
  # GET /academic_departaments/1.json
  def show
    authorize @academic_departament
  end

  # GET /academic_departaments/new
  def new
    @academic_departament = AcademicDepartament.new
    authorize @academic_departament
  end

  # GET /academic_departaments/1/edit
  def edit
  end

  # POST /academic_departaments
  # POST /academic_departaments.json
  def create
    @academic_departament = AcademicDepartament.new(academic_departament_params)
    authorize @academic_departament

    respond_to do |format|
      if @academic_departament.save
        format.html { redirect_to @academic_departament, notice: 'El departamento academico ha sido creado correctamente.' }
        format.json { render :show, status: :created, location: @academic_departament }
      else
        format.html { render :new }
        format.json { render json: @academic_departament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /academic_departaments/1
  # PATCH/PUT /academic_departaments/1.json
  def update
    respond_to do |format|
      authorize @academic_departament
      if @academic_departament.update(academic_departament_params)
        format.html { redirect_to @academic_departament, notice: 'Se ha actualizado el departamento academico correctamente.' }
        format.json { render :show, status: :ok, location: @academic_departament }
      else
        format.html { render :edit }
        format.json { render json: @academic_departament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /academic_departaments/1
  # DELETE /academic_departaments/1.json
  def destroy
    authorize @academic_departament
    @academic_departament.destroy
    respond_to do |format|
      format.html { redirect_to academic_departaments_url, notice: 'Se ha eliminado el departamento academico correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_academic_departament
      @academic_departament = AcademicDepartament.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def academic_departament_params
      params.require(:academic_departament).permit(:name, :code, :faculty_id)
    end
end

app/helpers/academic_departaments_helper.rb
module AcademicDepartamentsHelper
end

app/views/academic_departaments/_form.html.erb
<div class="card-text">
  <%= form_with(model: academic_departament, local: true) do |form| %>
    <% if academic_departament.errors.any? %>
      <%= render 'shared/error_messages', resource: academic_departament%>
    <% end %>

    <div class="form-group">
      <%= form.label :faculty_id, "Facultad" %>
      <%= form.select(:faculty_id, Faculty.all.collect { |f| [f.name, f.id ] }, {}, { id: "academic_departament_faculty_id", class: "form-control" }) %>
    </div>

    <div class="form-group">
      <%= form.label :name, "Nombre" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :code, "Codigo" %>
      <%= form.text_field :code, class: "form-control" %>
    </div>

    <div class="actions">
      <%= link_to(request.referrer, class: "btn btn-custom-2 float-right") do %>
        Volver atras
      <% end %>
      <%= form.submit "Enviar formulario", class: "btn btn-success btn-index-create float-right mr-2" %>
    </div>
  <% end %>
</div>

app/views/academic_departaments/edit.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Editar departamento academico</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Departamento academico</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= render 'form', academic_departament: @academic_departament %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/academic_departaments/index.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Departamentos academicos</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Listado de los departamentos academicos en la UFPS</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <% if !@academic_departaments.count.zero? %>
                  <div class="table-responsive">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th>Nombre</th>
                          <th>Codigo</th>
                          <th>Facultad</th>
                          <th colspan="3">Opciones</th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @academic_departaments.each do |academic_departament| %>
                          <tr>
                            <td><%= academic_departament.name %></td>
                            <td><%= academic_departament.code %></td>
                            <td><%= academic_departament.faculty.name %></td>
                            <td>
                              <%= link_to(academic_departament_path(academic_departament.id), class: "") do %>
                              <i class="fas fa-eye"></i>
                              <% end %>
                            </td>
                            <td>
                              <%= link_to(edit_academic_departament_path(academic_departament), class: "") do %>
                              <i class="fas fa-edit"></i>
                              <% end %>
                            </td>
                            <td>
                              <%= link_to(academic_departament_path(academic_departament.id), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "") do %>
                                <i class="fas fa-trash-alt"></i>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                  </table>
                  <%= link_to 'Crear nuevo programa academico', new_academic_departament_path, class: "btn btn-success btn-index-create float-right", role: "button" %>
                  </div>
                  <% else %>
                  <h2>No existen departamentos academicos en estos momentos, por favor, introduce los datos del programa academico y añadelo</h2>
                  <%= link_to 'Crear nuevo programa academico', new_academic_departament_path, class: "btn btn-success btn-index-create float-right", role: "button" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/academic_departaments/new.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Registrar un nuevo departamento academico</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <!-- /.card-header -->
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= render 'form', academic_departament: @academic_departament %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>

app/views/academic_departaments/show.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Datos del departamento academico</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <tbody>
                      <tr role="row" class="odd">
                        <td class="sorting_1">Codigo</td>
                        <td><%= @academic_departament.code %></td>
                      </tr>
                      <tr role="row" class="even">
                        <td class="sorting_1">Nombre</td>
                        <td><%= @academic_departament.name %></td>
                      </tr>
                      <tr role="row" class="odd">
                        <td class="sorting_1">Facultad a la que pertenece</td>
                        <td><%= @academic_departament.faculty.name %></td>
                      </tr>
                    </tbody>
                  </table>
                  <%= link_to(academic_departaments_path, class: "btn btn-custom-2 float-right ") do %>
                    Volver atras
                  <% end %>

                  <%= link_to(edit_academic_departament_path(@academic_departament), class: "btn btn-success float-right mr-2") do %>
                    Editar departamento academico
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </div>
    </div>
  </div>
</section>